### ISSUE TITLE
Help with 2 errors: Domain=NSCocoaErrorDomain Code=4099 | Print: Entry, ":Restart", Does Not Exist 

### ISSUE THREAD

**Issue by cmscholz222** [SecondSonConsulting/Baseline#13]
Hi, I've been working on getting Baseline up and running to replace my current process which combines SYM & Installomator (most apps aside from Sophos installed via Installomator). I'm hoping to switch over by the end of the month but can't seem to get past the 2 errors (lines: 4, 6, etc.) mentioned in the title of this issue report. 

I'm testing on Intel and arm64; macOS Monterey for all test devices. I'm using an initial script (saved to /usr/local/Baseline/Scripts), have all dept. scripts set up (saved to /usr/local/Baseline/Scripts), using a custom baselineconfig.plist (saved to /usr/local/Baseline/) modeled on the original from Github. 

The com.secondsonconsulting.baseline.plist file has been placed in /Library/LaunchDeamons/. I packaged all of my changed files (including the post and pre-install scripts [saved to /usr/local/Baseline/Scripts]) using Packages (I've attached a screenshot of the build). 

I'm using Jamf Pro (Cloud) v10.47.0, and plan to eventually post up the working process to Second Son's GitHub repo for Baseline. 

![Screen Shot 2023-07-19 at 9 44 53 AM](https://github.com/SecondSonConsulting/Baseline/assets/2805849/7b7cd0d3-4280-4f2a-83d3-3d5b9a0b84f9)

Here is what the log from the latest Run attempt looks like:

(I'm thinking perhaps Option is actually "variable" in Jamf? Not sure what variable 4 in Jamf would be then (from the current Baseline.sh v1.2 script, as a predecessor to 5...)

1. +wait_for_user:29> date +%s
2. +wait_for_user:29> debug_message 'Re-enabling verbose output after finding user at timestamp: 1689706400'
3. +debug_message:2> [ '' '=' 1 ']'
>>>>>> 4. **Print: Entry, ":Restart", Does Not Exist**
5. check_restart_option:5: parse error: condition expected: =
>>>>>> **6. 2023-07-18 14:53:20.952 Dialog[4424:30484] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}**
7. 2023-07-18 14:53:20.952 Dialog[4424:30484] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
8. 2023-07-18 14:53:20.952 Dialog[4424:30484] XType: unable to make a connection to the font daemon!
9. 2023-07-18 14:53:20.952 Dialog[4424:30484] XType: XTFontStaticRegistry is enabled as fontd is not available.
10. 2023-07-18 14:53:22.005 Dialog[4478:30695] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
11. 2023-07-18 14:53:22.005 Dialog[4478:30695] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
12. 2023-07-18 14:53:22.005 Dialog[4478:30695] XType: unable to make a connection to the font daemon!
13. 2023-07-18 14:53:22.005 Dialog[4478:30695] XType: XTFontStaticRegistry is enabled as fontd is not available.
14. 2023-07-18 14:53:33.202 Dialog[4478:30743] Spell server connection invalidated
15. Print: Entry, ":Restart", Does Not Exist
16. check_restart_option:5: parse error: condition expected: =
17. Print: Entry, ":CleanupAfterUse", Does Not Exist
18. Shutdown NOW!
19. 
20. System shutdown time has arrived

Please let me know if you need anymore info, and thanks a lot in advance, Charley (Senior Systems Admin, Jamf Admin, NYC. NY)

**Comment by BigMacAdmin** [comment]
I'm sorry for the late response on this, i'm not sure how i missed this Issue.

I know that some versions of SwiftDialog have some benign font errors like this, and I suspect the messages you're seeing are related to that. 

The `Print: Entry "Restart" Does Not Exist` are also benign, and something I need to clean up in the code. Baseline is checking if that key exists in your configuration profile, and it should fail silently but apparently it's not. i'll check for that as I'm doing some dev right now.

Is this issue still happening for you?

**Comment by BigMacAdmin** [comment]
the "Print: Entry xxx Does Not Exist" errors are corrected in the latest updates, closing this issue.
