### ISSUE TITLE
Ventura 13.5 dialog installation failed

### ISSUE THREAD

**Issue by mkennard20** [SecondSonConsulting/Baseline#21]
Baseline failing to open saying.
Dialog installation failed
Dialog not found. Installing. Further down in the log it says SwiftDialog failed to install after numerous attempts.

**Comment by mkennard20** [comment]
Going to test on older versions and see when it started

**Comment by mkennard20** [comment]
Just subscribed to Slack and saw the error posted. I'll see if the fix works for me

**Comment by mkennard20** [comment]
Installing dialog worked.

**Comment by mkennard20** [comment]
Ran this first
https://github.com/swiftDialog/swiftDialog/releases/tag/v2.3.1

**Comment by BigMacAdmin** [comment]
Thanks for your patience, and Baseline v1.2.1 was just released and should resolve this for you
