### ISSUE TITLE
Basic v1.0 Intune documentation

### ISSUE THREAD

**Issue by pattiobear** [SecondSonConsulting/Baseline#27]
# Microsoft Intune

## General Guidance for Using Baseline with Microsoft Intune
Groups in Intune (especially dynamic groups) are slow to update as group data is stored in AzureAD and there is a delay in syncing between Intune and AzureAD. For time-sensitive deployments (e.g. zero-touch) it's recommended to scope to All Users or All Devices and narrow scope using [device filters](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMenu/~/assignmentFilters) if possible. See Microsoft's documentation [here](https://learn.microsoft.com/en-us/mem/intune/fundamentals/filters).
Many thanks to Luke Hawkins, Chris McFall, and Johan Kjellman in the MacAdmins Slack for providing the foundation of most of this documentation.

## Configuration Profile
Customize the mobileconfig file as desired. Signing the profile is not required. Then upload it to Intune: 
1. Navigate to [Devices - macOS - Configuration Profiles](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMacOsMenu/~/configProfiles). 
2. Click Create, click "New Policy", and select the "Templates" profile type. 
3. Click "Custom" and click "Create".
4. Enter a name and description and click Next.
5. Enter a name for the configuration profile, deploy to Device channel, upload the configuration file, and click Next.
6. Assign as desired and click Next.
7. Click Create.

## Zero Touch
For a successful zero-touch experience, use a script to deploy Baseline. Due to delays when Intune deploys packages, Baseline is unlikely to run when needed if deployed as a package.

### Deploy the script version of Baseline
1. Download Baseline.sh and customize as desired. Be sure to add an exit condition. Here is an example from Johan Kjellman:
```
#################################
# Look for Company Portal.app #
# Abort deploy if it exists #
# This portion written by Johan Kjellman #
#################################
Company_Portal="/Applications/Company Portal.app/Contents/Info.plist"
echo "Checking if computer is already deployed"
if [ -f "$Company_Portal" ]; then
echo "Already deployed"
exit 0
else
echo "Continuing deployment"
fi
```
2. In Intune, navigate to [Devices - macOS - Shell scripts](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMacOsMenu/~/shellScripts).
3. Click Add. Enter a name and click Next.
4. Upload the script.
5. Change "Run script as signed-in user" to "No".
6. Change "Max number of times to retry if script fails" to 3 and click Next.
7. Assign to all users and click Next.
8. Review settings and click Add.

### Use a script to download and run a pkg version of Baseline
If you wish to repackage the pkg version and add additional pkg files: Customize as desired, then upload to your desired location (cloud/local network storage).
Create a shell script that downloads and installs the pkg from Github or the location of your customized pkg.

### Company Portal
By default, Baseline does not install anything to the device. Therefore, Intune has no way of detecting if Baseline successfully "installed". Customize the pkg file so it "installs" an app to put in the detection rules.
To run Baseline on-demand via the Company Portal, complete the following steps:
1. Download Baseline.pkg and customize it as desired.
3. In Intune, navigate to [Apps - macOS](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/AppsMacOsMenu/~/macOsApps) and click Add.
4. Select "macOS app (PKG)" as the app type and click Select.
5. Upload the pkg file, fill out the information, and click Next. 
6. Add pre or post-install scripts and click Next.
8. Set the minimum OS. Baseline is compatible with macOS 11 or newer, but if you added additional pkg files, they may have higher minimum OS requirements.
9. Set the detection rules based on how you've customized the package.
10. Assign as desired and click Next.
11. Click Create.

**Comment by pattiobear** [comment]
Also FYI, Intune is in the "looking for documentation" sidebar twice: 
<img width="256" alt="image" src="https://github.com/SecondSonConsulting/Baseline/assets/32683613/1f4fb1c9-f4e6-4f68-b766-ad6a7a286299">

**Comment by pattiobear** [comment]
# Microsoft Intune

## General Guidance for Using Baseline with Microsoft Intune
Groups in Intune (especially dynamic groups) are slow to update as group data is stored in AzureAD and there is a delay in syncing between Intune and AzureAD. For time-sensitive deployments (e.g. zero-touch) it's recommended to scope to All Users or All Devices. Narrow scope by using Intune-native [device filters](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMenu/~/assignmentFilters) ([Microsoft documentation](https://learn.microsoft.com/en-us/mem/intune/fundamentals/filters)).
Many thanks to Luke Hawkins, Chris McFall, and Johan Kjellman in the MacAdmins Slack for providing the foundation of most of this documentation.

## Configuration Profile
Customize the mobileconfig file as desired. Signing the profile is not required. Then upload it to Intune: 
1. Navigate to [Devices > macOS > Configuration Profiles](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMacOsMenu/~/configProfiles). 
2. Click **Create**, click **New Policy**, and select the **Templates** profile type. 
3. Click **Custom** and click **Create**.
4. Enter a name and click **Next**.
5. Enter a name for the configuration profile, deploy to Device channel, upload the configuration file, and click **Next**.
6. Assign as desired and click **Next**.
7. Click **Create**.

## Zero Touch
For a successful zero-touch experience, use a script to deploy Baseline. Due to delays when Intune deploys packages, Baseline is unlikely to run when needed if deployed as a package. When deploying via a script, ensure there is an [ExitCondition](https://github.com/SecondSonConsulting/Baseline/wiki/Defining-Additional-Features#configuring-exitcondition) specified in the configuration profile.

### Deploy the script version of Baseline
1. Download Baseline.sh and customize as desired. 
2. In Intune, navigate to [Devices - macOS - Shell scripts](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMacOsMenu/~/shellScripts).
3. Click **Add**. Enter a name and click **Next**.
4. Upload the script.
5. Change **Run script as signed-in user** to **No**.
6. Change **Max number of times to retry if script fails** to **3**. Leave the other options unconfigured and click **Next**.
7. Assign to all users and click **Next**.
8. Review settings and click Add.

### Use a script to download and run a package version of Baseline
If you wish to add additional pkg files to the package version: Download Baseline.pkg, customize, then repackage and upload to your desired location (cloud or local network storage).
Create a shell script that downloads and installs the default package from Github or the customized package from your network location.

## On-Demand/Self-Service
### Company Portal
By default, Baseline does not install anything to the device. Therefore, Intune has no way of detecting if Baseline successfully "installed". Customize the pkg file so it "installs" an app to specify in the detection rules (these cannot be blank).
To deploy Baseline for on-demand use via the Company Portal, complete the following steps:
1. Download Baseline.pkg and customize it as desired.
2. In Intune, navigate to [Apps > macOS](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/AppsMacOsMenu/~/macOsApps) and click **Add**.
3. Select **macOS app (PKG)** as the app type and click **Select**.
4. Upload the pkg file, fill out the information, and click **Next**. 
5. Add pre or post-install scripts if desired and click **Next**.
6. Set the minimum OS. Baseline is compatible with macOS 11 or newer, but if you added additional pkg files, they may have higher minimum OS requirements. Cllck **Next**.
7. Set the detection rules based on how you've customized the package and click **Next**.
8. Assign as desired and click **Next**.
9. Click **Create**.

**Comment by BigMacAdmin** [comment]
Thank you again for this!

https://github.com/SecondSonConsulting/Baseline/wiki/Microsoft-Intune
