### ISSUE TITLE
General Guidance for Using Baseline with JumpCloud

### ISSUE THREAD

**Issue by juergen-kc** [SecondSonConsulting/Baseline#29]
**General Guidance for Using Baseline with JumpCloud**
[Link](https://community.jumpcloud.com/t5/community-scripts/how-to-baseline-literally-your-macos-in-a-breeze-using-jumpcloud/td-p/3979) to Community Post

**Configuration Profile**
Best method is deploy it via a [Custom Policy](https://jumpcloud.com/support/create-mac-or-ios-mdm-custom-configuration-profile-policy) for macOS

**Zero Touch**
This can be achieved by deploying the PKG for Baseline via Software Management and assigning it to (Dynamic) Group of Devices. Same applies for the Configuration Profile. Ideally the device will come through DEP via ABM. 

On-Demand/Self-Service
Any specific guidance on how to run Baseline "on demand" (not in a fully automated fashion)

**Comment by BigMacAdmin** [comment]
https://github.com/SecondSonConsulting/Baseline/wiki/Using-Baseline-via-JumpCloud

Added to the wiki.

Thank you again for your contribution!
