### ISSUE TITLE
Using Baseline with Jamf Pro

### ISSUE THREAD

**Issue by dpertschi** [SecondSonConsulting/Baseline#36]
# General Guidance for Using Baseline with Jamf Pro

Baseline is very easily deployed from Jamf Pro and can be leveraged in a variety of ways. 
Please read the whole [Wiki](https://github.com/SecondSonConsulting/Baseline/wiki/How-it-Works) first to understand what’s going on and what your options are.

# Configuration Profile

When using a configuration profile to manage Baseline you can roll your own or use iMazing Profile Editor for an assist, but you may find it easier to use the automatically generated [JSON schema](https://github.com/ProfileCreator/ProfileManifests/blob/master/Manifests/ManagedPreferencesApplications/com.secondsonconsulting.baseline.plist).

If you want the JSON for a current **beta** release of Baseline, go to the main GitHub page, switch from the **main** branch to the **dev** branch, click on the **ProfileManifest** folder link and you should find the JSON link within.

<img width="350" alt="baseline dev branch" src="https://github.com/SecondSonConsulting/Baseline/assets/16840386/0c82e01d-6b7d-455e-9d43-bde7c3d38b9c">

## Using the JSON - here’s how

- Copy the raw JSON code to the clipboard
- In Jamf Pro, create a new Configuration Profile and complete the **General** fields as desired
- In the **Application & Custom Settings** options > **External Applications** > choose **Custom Schema** as the **Source**
- Set the **Preference Domain** to _com.secondsonconsulting.baseline_
- Click on the **Add Schema** button

<img width="550" alt="Jamf ext apps config" src="https://github.com/SecondSonConsulting/Baseline/assets/16840386/1eeeb79b-15e2-4fbe-b2bb-04f34e8fb6ca">

,,

In the **Custom JSON Schema** dialog, paste the code into the box, click **Upload** and **Save**
,,

<img width="550" alt="Jamf custom schema" src="https://github.com/SecondSonConsulting/Baseline/assets/16840386/0ad92c5a-f3a5-49f7-8ad8-4a7f0275c397">

,,
You’ll now see all the configurable properties in the GUI. You do not need to use all the properties provided. For instance, if you don’t need **InitialScripts** and wont use **Installomator**, you can safely click on **Add/Remove Properties** and uncheck those options. Need them later, just add them back.

<img width="350" alt="add remove properties" src="https://github.com/SecondSonConsulting/Baseline/assets/16840386/891442d1-1770-4f0e-a22f-a6e52a7ebb11">

When a new version of Baseline is released you can easily update the schema by clicking on the **Edit Schema** button and pasting in the new JSON code.

# Using the Scripts properties to run Jamf policies

The basic use of Scripts, Installomator, and Packages is well documented within the wiki, however the Scripts properties offer some unique flexibility for Jamf users. In addition to running an actual shell script, you can point to the Jamf binary and define a _Custom Event_ trigger to run an entire Jamf policy.

For example; if you have a policy that installs Microsoft Office with a custom trigger of _Install_MicrosoftOffice_, configure the **Script Path** and **Arguments** like this:

<img width="400" alt="Script Path and Arguments" src="https://github.com/SecondSonConsulting/Baseline/assets/16840386/18ecae02-8f23-4504-8805-5bccb31fcda3">

Finally, ensure your configuration profile is scoped to a group that will encompass your target machines after enrollment.

# Zero-Touch

### To use Baseline in your Automated Device Enrollment workflow as a user facing progress dialog

Create your configuration profile with desired settings for packages, scripts, dialog window options, etc.

Create/Modify your Jamf PreStage Enrollment options:
- 	Add the Baseline installer package (including the LaunchDaemon) to the **Enrollment Packages** section
- 	Ensure your Baseline configuration profile is enabled in the **Configuration Profiles** section

With those things in place, after enrollment when a user logs in, Baseline will trigger and begin processing your configurations.

**Comment by BigMacAdmin** [comment]
Thank you again for this! 

[https://github.com/SecondSonConsulting/Baseline/wiki/Darrin-Pertschi-%E2%80%90-Using-Baseline-with-Jamf-Pro](https://github.com/SecondSonConsulting/Baseline/wiki/Darrin-Pertschi-%E2%80%90-Using-Baseline-with-Jamf-Pro)
