### ISSUE TITLE
MDM deploy support

### ISSUE THREAD

**Issue by hachirotahoshino** [SecondSonConsulting/Baseline#42]
We would need a way to supervise deployment from MDM:

1) by checking deployed apps presence (check .app folder presence or event executable presence in .app/Contents/MacOS/)

2) by checking the content of a defined txt file where all the scripts deployed note what is done 

each script would create a file *.proof in the /Users/Shared/ folder
(ie: mainuserprivilegedrevoke.proof defaultbrowserandmailsetted.proof,...)

The information we would need to fill in a configuration profile:

- the list of apps / executable and eventually full name/path
- the location of the proof file (default /Users/Shared
- the list of proof files to check for presence

Thanks a lot if you could integrate this

**Comment by LukeEvansTech** [comment]
Having the ability to poll for the presence of an app deployed by VPP would be ideal - as a minimum MVP I would just need check for the location of the file "/Apps/Company Portal.app" for example.

**Comment by BigMacAdmin** [comment]
This has been included in the latest 2.2 release
