### ISSUE TITLE
Feature Idea: `InfoBox.md` in Baseline folder will be used as the SwiftDialog infobox feature

### ISSUE THREAD

**Issue by BigMacAdmin** [SecondSonConsulting/Baseline#46]
It's not possible to add dynamic info into the SwiftDialog "infobox" currently. If we made a feature to just use whatever is in `/usr/local/Baseline/InfoBox.md` as the infobox contents, then folks can use an initial script to set that file up and make full use of that SwiftDialog feature.

**Comment by BigMacAdmin** [comment]
Maybe an accompanying configuration key so that users can set a custom location for that .md file?

**Comment by bartreardon** [comment]
> It's not possible to add dynamic info into the SwiftDialog "infobox" currently.

From a baseline standpoint or a swiftdialog standpoint? you can do the latter with `echo "infobox: <markdown text here>" >> /path/to/commandfile.log`

**Comment by BigMacAdmin** [comment]
From a Baseline standpoint. Currently the only way to populate the InfoBox in Baseline is to configure your messaging in the config file itself, making it require backflips if you wanted to do that.

I'm aiming to make it easier by allowing folks to make an .md file from a script or another process, then let Baseline pick that up

**Comment by bartreardon** [comment]
that gives me an idea

**Comment by BigMacAdmin** [comment]
Closing this out w/out implementing. This can easily be accomplished with an `InitialScript` and the features Bart is adding to Dialog 2.5 will make this even better.
