### ISSUE TITLE
Feature Request: Catalog App Installations Support

### ISSUE THREAD

**Issue by PinkShellos** [SecondSonConsulting/Baseline#54]
I couldn't tell from the existing codebase, but I think having support for apps deployed via an App Catalog (Jamf App Installers, Mosyle Apps, VPP, etc.) would be a good, forward thinking feature.

It could be implemented in the same way [Octory](octory.io) handles this, with a list of app titles that it can check for the existence of by appending .app to the end of the display name.

Example:
```bash
installStatus="false"

if [ -e "/Applications/$APP_NAME.app" ]; then
    installStatus="true"
else
    sleep 2
fi
```

Obviously, this doesn't have all the logic/syntax to make it run smoothly, but you get the idea. 😉

**Comment by PinkShellos** [comment]
PR #57 submitted 😄

**Comment by BigMacAdmin** [comment]
I apologize I didn't reply to this right away, I think it got mixed up in our other messages you sent.

This was already added to Baseline in v2.2. Apparently I failed to add the appropriate documentation to the wiki, which I will attend to shortly.

You can review the `WaitFor` feature settings in the release notes: https://github.com/SecondSonConsulting/Baseline/releases

Very sorry to have wasted your time, but I think this already does what you need?

**Comment by PinkShellos** [comment]
I just figured that out as I was reviewing my code for why isn't this working exactly as I thought it would. 😫

Welp, I'll close that out since v2.2 had that. Perhaps an update to a more appropriate name for the key? I didn't realize that was what `WaitFor` was meant to solve.

Thank you for the clarification!

**Comment by BigMacAdmin** [comment]
I don't think I want to change the key, but I'm open to suggestions on how to label it for easy discovery in documentation.
